---

- name: Deploy Todo Web Application
  hosts: localhost
  connection: local
  roles:
    - { role: bootstrap_linux, when: bootstrap == 'yes' }
    - { role: setup_minikube, when: deploy }
    - { role: deploy_todo_application, when: deploy }
    - { role: teardown_minikube, when: not deploy }